language: node_js
node_js:
    - "node"
services:
    - xvfb
cache:
    directories:
        - ~/.npm
        - ~/.cache
jobs:
    include:
        - stage: "Tests"
          name: "Jest Tests"
          script: yarn test
        - name: "Cypress Tests"
          script:
              - yarn dev
              - sleep 5
              - yarn run cypress
