name: Test

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: yarn install
            - name: Run Jest tests
              run: yarn test
            - name: Run Cypress tests
              run: yarn cy:run
