name: Test

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: yarn install
            - name: Run Jest tests
              run: yarn test
            - name: Scrutiny
              uses: actions/checkout@v2

            - name: Cypress run
              uses: cypress-io/github-action@v3
              with:
                  project: ./scrutiny-2.0
                  browser: chrome
                  build: yarn build
                  start: yarn start
                  wait-on: "http://localhost:3000"
              env:
                  NEXT_PUBLIC_CONTENTFUL_SPACE_ID: v5y50stioip2
                  NEXT_PUBLIC_CONTENTFUL_API_KEY: 6pUnN-Lhc_pwsWrwWzBmfeNzobTt8arCeHnnICxPcdk
